### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by kwadroke** [prasannax1/starships#60]
How is this project licensed? I don't see a License file or info in the Readme.

I was thinking about using your models as a mod for the game [Empty Epsilon](https://github.com/daid/EmptyEpsilon/). It's a Spaceship Bridge Simulator; basically a multiplayer Star Trek like game. Depending on what license it's under, it could affect how I could distribute it.

**Comment by prasannax1** [comment]
Licensed as creative commons - hopefully the one that says use it as you want but make sure to mention my name.

**Comment by kwadroke** [comment]
Thank you. Will do.
